### ISSUE TITLE
Denormalize field names for wes api

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/rdpc-gateway#14]
Currently, gql queries are normalized. For example:
```
{
  "donor" : {
        "id"  : "DO1",
        "submittedId" : "K_DO1",
        "specimen" : {
              "id"  : "SPO1",
              "submittedId" : "K_SPO1",
        }
  }
}
```

Instead, the fields should be de-normalized. For example:
```
{
  "donor" : {
        "donorId"  : "DO1",
        "submitterDonorId" : "K_DO1",
        "specimen" : {
              "specimenId"  : "SPO1",
              "submitterSpecimenId" : "K_SPO1",
        }
  }
}
```

The field names should match argo-clinical field names as close as possible.

**Comment by rosibaj** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/RDPC+Gateway+Design

The schema here was design with this in mind, so closing this ticket
