### ISSUE TITLE
Design: Authorization policy strategy for RDPC services

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/rdpc-gateway#35]
There will be multiple RDPCs ( ex. once in Canada and one in Germany).  Based on this, each RDPC needs to be individually scoped for access so that members with access to one RDPC cannot access data at other RDPCs.Data from different RDPCs should not be accessible to other RDPCs (both members and workflow systems)

- [ ] Need to define RDPC specific scope rules.  What should the scopes for each RDPCS look like? How many will we need for each RDPC? 
- Verify that rdpc specific song/score are using rdpc specific scopes in authorization (ex song.collab.write, not song.write)

**Comment by andricDu** [comment]
@jaserud connect with me if you need some background or extra details on this.

**Comment by andricDu** [comment]
Rescoped to just design.

**Comment by andricDu** [comment]
Acceptance Criteria as discussed: Spec on the Wiki outlining a matrix of services that are part of RDPC architecture, their operations, and accepted scopes for those operations.

**Comment by rosibaj** [comment]
Linking for future folllow-up: 
https://github.com/icgc-argo/workflow-search/issues/83
https://github.com/icgc-argo/song-search/issues/15

**Comment by jaserud** [comment]
@andricDu As discussed, I've documented the strategy here: https://wiki.oicr.on.ca/display/icgcargotech/RDPC+Services+-+Authorization+policy+strategy. Let me know what you think.

**Comment by andricDu** [comment]
So one thing to consider is that there may be users, for example data submitters, who need access to upload to song/score for submission, but will not have access to view or launch a workflow.

So we already have the policies of `song` and `score` which we can rename to something like `song-ca` and `score-ca` for the Canadian RDPC as you already mentioned in the spec. 

For the RDPC API you may need a new policy. 

Think of it this way, both Song and Score are their own bounded contexts in our domain. Workflows (RDPC operations) are now a new aspect and bounded context for our domain. It would probably follow that we would like a new level of access controls for that context.

Some background info on DDD:
https://en.wikipedia.org/wiki/Domain-driven_design#Bounded_context
https://martinfowler.com/bliki/BoundedContext.html

**Comment by andricDu** [comment]
Using a ISO country code suffix is a great idea in the policy name. I think it would make sense if we use alpha-2 instead of alpha-3 as that is what we already do in the platform for program registration.

**Comment by jaserud** [comment]
@andricDu Feedback changes applied to doc :ok_hand:. Take a look when you get a chance: https://wiki.oicr.on.ca/display/icgcargotech/RDPC+Services+-+Authorization+policy+strategy
