### ISSUE TITLE
Feature Request - More Donor Data

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/rdpc-gateway#44]
Need to get all runs for a study to update.  for those runs, know STATE and which donor (have to go thru analysis right now, but analysis does not always exist) 
- minh has donor id and study id, but needs runs. 
- we are not including all analyses, so he can't query for all the runs he is interested in
- Proposal: Clinical shim to enrich donor centric graphQL with run entities
-- new entry point into the graph via donor.

**Comment by jaserud** [comment]
After further investigation it was agreed that the current data model in RDPC-gateway does have enough information to get required data. Rather then query for all `runs` based on repository and filter/map on `inputAnalyses`, start with `analyses` of type `sequencing_experiment` and traverse into the graph with `inputForRuns` all the way to `variant_calling` level checking for the state of the runs. The `analyses` query already provides filtering options for `sutdyId` and `donorId`.
