### ISSUE TITLE
Fix Jenkins Tag Automation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/rdpc-gateway#45]
Jenkins is not automatically creating github tags in gateway.  looks like service is not tagged when it is

**Comment by yalturmes** [comment]
The changes necessary to enable git tagging have already been addressed in this ticket:
https://github.com/icgc-argo/song-search/issues/27
And merged into develop branch:
https://github.com/icgc-argo/rdpc-gateway/pull/46

In order for the changes to take effect in Jenkins CI - develop needs to be merged to master. I spoke with @lepsalex to provide details.

**Comment by lepsalex** [comment]
will need a new release of rdpc-gateway

**Comment by akachru-github** [comment]
Hi @lepsalex , any luck getting this change merged and released? Let me know if you need anything from us!

**Comment by akachru-github** [comment]
https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/rdpc-gateway/53 is closed. This ticket will now be closed.
