### ISSUE TITLE
🐛 T/N Pair query only works for type Normal 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/rdpc-gateway#61]
Against prod:  https://api.rdpc.cancercollaboratory.org/graphql

# Description 
RDPC T/N query is not reporting all tumour pairs for a donor. 

# Steps to Reproduce
## 1. Query using the Normal Analysis ID, get 1 pair 
![image](https://user-images.githubusercontent.com/15824252/110179412-07119c00-7dd6-11eb-9c8d-10f75ee849e8.png)

Query 
```
query {
  sampleMatchedAnalysisPairs (analysisId:"82c9f309-6123-4593-89f3-0961235593cb"){
    normalSampleAnalysis{
      analysisId
    }
    tumourSampleAnalysis{
      analysisId
    }
  }
}
```

## 2. Query using the Tumour Analysis ID - 72886e52-343c-4ffb-886e-52343ccffbd9 - get no results 
![image](https://user-images.githubusercontent.com/15824252/110179710-8acb8880-7dd6-11eb-990a-be01f3a337ab.png)
```
query {
  sampleMatchedAnalysisPairs (analysisId:"72886e52-343c-4ffb-886e-52343ccffbd9"){
    normalSampleAnalysis{
      analysisId
    }
    tumourSampleAnalysis{
      analysisId
    }
  }
}
```
## 3. Look at Analysis ID - 72886e52-343c-4ffb-886e-52343ccffbd9 - look for matched pair 
![image](https://user-images.githubusercontent.com/15824252/110179776-a8005700-7dd6-11eb-8d9f-32aba5a44cac.png)
```
query{
  analyses (filter: {
    analysisId: "72886e52-343c-4ffb-886e-52343ccffbd9"
  }){
    info{
      totalHits
      contentCount
      hasNextFrom
    }
    content{
      analysisId
      donors {
        donorId
        submitterDonorId
        specimens {
          specimenId
          tumourNormalDesignation
          samples{
            matchedNormalSubmitterSampleId
            submitterSampleId
            sampleId
          }
        }
      }
    }
  }
}
```

## 4. Look at all donor sequencing_experiment. this has 4 tumours paired to this normal 
![image](https://user-images.githubusercontent.com/15824252/110180412-ba2ec500-7dd7-11eb-9d8d-873cf8252155.png)
```
query{
  analyses (filter: {
    donorId: "DO35140",
    analysisType: "sequencing_experiment"
  }){
    info{
      totalHits
      contentCount
      hasNextFrom
    }
    content{
      analysisId
      donors {
        donorId
        submitterDonorId
        specimens {
          tumourNormalDesignation
          samples{
            matchedNormalSubmitterSampleId
            submitterSampleId
          }
        }
      }
    }
  }
}
```

# Expected Behavior 
if i query for any 4 of these tumours, the T/N query should return that there is a pair, not just one pair.

**Comment by Buwujiu** [comment]
@rosibaj Verified on my end that the bug still exists in rdpc prod api.

**Comment by rosibaj** [comment]
@Buwujiu does this summary match what you were saying?

**Comment by Buwujiu** [comment]
@rosibaj Yes it does!

**Comment by rosibaj** [comment]
From Jaser: the query is not returning a matched pair bc they are different `experimental_strategies`.  You can see this that they are WXS and WGS.  here is an example query comparing the two: 
```
query mismatch_on_matched_normal {
  tumourWXS: analyses(
    filter: { analysisId: "72886e52-343c-4ffb-886e-52343ccffbd9" }
  ) {
    content {
      experiment
      donors {
        donorId
        submitterDonorId
        specimens {
          tumourNormalDesignation
          samples {
            matchedNormalSubmitterSampleId
            submitterSampleId
          }
        }
      }
    }
  }
  normal: analyses(
    filter: { analysisId: "82c9f309-6123-4593-89f3-0961235593cb" }
  ) {
    content {
      experiment
      donors {
        donorId
        submitterDonorId
        specimens {
          tumourNormalDesignation
          samples {
            matchedNormalSubmitterSampleId
            submitterSampleId
          }
        }
      }
    }
  }
}
```
