### ISSUE TITLE
Error on gql query for analysis.workflow.run.runId

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/rdpc-gateway#81]
Queries for to get run from analysis is returning errors in rdpc-qa.

Steps to produce:
1. Go to gql in rdpc-qa env
2. Run this query
```
{
  analyses (filter:{analysisType:"variant_calling", analysisState:PUBLISHED}, sorts: {fieldName: publishedAt, order: desc}) {
    content {
        workflow {  
          runId
          run {
            runId
          }
        }
    }    
  }
}
```
3. See the error
```
  "errors": [
    {
      "message": "Expected \"data._entities\" to contain 10 elements",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": { ... }
      }
    }
  ]
```

- Most likely whats happening is these analysis are pointing to non-existing workflows (is that possible?)
- We should correctly indicate this info some how instead of showing an error

**Comment by Buwujiu** [comment]
The query is working in QA, error is not reproducible anymore, closing.
